name: algolia_model
description: Extension of firebase_model to handle algolia snapshots
version: 1.1.0
author: Roland Volskaya
homepage: github.com/volskaya/algolia_model
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  algolia: ^1.0.1
  cloud_firestore: ^1.0.1
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1

  firestore_model:
    path: /home/projects/packages/firestore_model

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^4.1.0
  freezed: ^0.14.1+1

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
