name: algolia_model
description: Extension of firebase_model to handle algolia snapshots
version: 1.1.0
homepage: github.com/volskaya/algolia_model
publish_to: none

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  algolia: ^1.0.1
  cloud_firestore: ^3.1.6
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  firestore_model:
    path: /Users/muru/Projects/packages/firestore_model

dev_dependencies:
  build_runner:
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1
